In [2]:
import numpy as np

def mult_scalar(m, s):
    matrix = np.empty(m.shape)
    m_shape = m.shape
    for i, v in enumerate(range(m_shape[0])):
        result = [x * s for x in m[v]]
        x = np.array(result[0])
        matrix[i] = x
    return matrix

def display(m):
    s = np.shape(m)
    cols = s[1]
    for i, row in enumerate(m):
        print('row', str(i) + ':', row, 'elements:', end=' ')
        for col in range(cols):
            print (row[col], end=' ')
        print ()

In [3]:
v1, v2, v3 = [1, 7, -4], [2, -3, 10], [3, 5, 6]
A = np.matrix([v1, v2, v3])

In [4]:
A

matrix([[ 1,  7, -4],
        [ 2, -3, 10],
        [ 3,  5,  6]])

In [5]:
scalar = 0.5
B = mult_scalar(A, scalar)
B

array([[ 0.5,  3.5, -2. ],
       [ 1. , -1.5,  5. ],
       [ 1.5,  2.5,  3. ]])

In [6]:
mu_col = np.mean(A, axis=0, dtype=np.float64)
mu_col

matrix([[2., 3., 4.]])

In [7]:
mu_row = np.mean(A, axis=1, dtype=np.float64)
mu_row

matrix([[1.33333333],
        [3.        ],
        [4.66666667]])

In [8]:
C = np.array([[2, 14, -8], [4, -6, 20], [6, 10, 12]])
C

array([[ 2, 14, -8],
       [ 4, -6, 20],
       [ 6, 10, 12]])

In [9]:
display(C)

row 0: [ 2 14 -8] elements: 2 14 -8 
row 1: [ 4 -6 20] elements: 4 -6 20 
row 2: [ 6 10 12] elements: 6 10 12 


In [10]:
def sum_cols(matrix):
    return np.sum(matrix, axis=0)

def sum_rows(matrix):
    return np.sum(matrix, axis=1)

def dot(v, w):
    return np.dot(v, w)

In [11]:
v1, v2, v3 = [1, 7, -4], [2, -3, 10], [3, 5, 6]
A = np.matrix([v1, v2, v3])

In [12]:
A

matrix([[ 1,  7, -4],
        [ 2, -3, 10],
        [ 3,  5,  6]])

In [13]:
v_cols = sum_cols(A)

In [14]:
v_cols

matrix([[ 6,  9, 12]])

In [16]:
v_rows = sum_rows(A)
v_rows

matrix([[ 4],
        [ 9],
        [14]])

In [17]:
dot_product = dot(v1, v2)
dot_product

-59

In [18]:
v1, v2, v3 = [-2, 5, 4], [1, 2, 9], [10, -9, 3]
B = np.matrix([v1, v2, v3])

In [19]:
B

matrix([[-2,  5,  4],
        [ 1,  2,  9],
        [10, -9,  3]])

In [20]:
C = A.dot(B)
C

matrix([[-35,  55,  55],
        [ 93, -86,  11],
        [ 59, -29,  75]])

In [21]:
def dot(v, w):
    return np.dot(v, w)
def display(m):
    for i, row in enumerate(m):
        print ('total sales by day:\n', end='')
        for v in np.nditer(row):
            print (v, end=' ')
        print()

In [23]:
a = [3, 4, 2]
A = np.matrix([a])
A

matrix([[3, 4, 2]])

In [25]:
v1, v2, v3 = [13, 9, 7, 15], [8, 7, 4, 6], [6, 4, 0, 3]
B = np.matrix([v1, v2, v3])
B

matrix([[13,  9,  7, 15],
        [ 8,  7,  4,  6],
        [ 6,  4,  0,  3]])

In [26]:
C = A.dot(B)
C

matrix([[83, 63, 37, 75]])