In [4]:
"""A simple TensorFlow application"""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import tensorflow as tf


In [7]:
# Create tensor
rnd_ints = tf.random_normal([10], dtype=tf.float64)# Launch session
a = tf.constant([3, 3, 3])
b = tf.constant([2, 2, 2])
div1 = tf.divide(a, b)
div2 = a / b
div3 = tf.div(a, b)
div4 = a // b

In [9]:
with tf.Session() as sess:
    print(sess.run(rnd_ints))
    print(sess.run(div1))
    print(sess.run(div2))
    print(sess.run(div3))
    print(sess.run(div4))

[ 0.83556459 -1.64029684  1.21756988 -2.07663768  1.65894939  1.13248849
 -1.15043865  0.76910991  0.19226363 -0.59345665]
[1.5 1.5 1.5]
[1.5 1.5 1.5]
[1 1 1]
[1 1 1]


In [10]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])

In [11]:
dot = tf.tensordot(t1, t2, 1)

In [12]:
with tf.Session() as sess:
    print(sess.run(dot))

20.0


In [13]:
t1 = tf.constant([[1., 2., 3.], [4., 5., 6.]])
t2 = tf.constant([[1., 2.], [3., 4.], [5., 6.]])

In [14]:
dot = tf.matmul(t1, t2)

In [15]:
with tf.Session() as sess:
    print(sess.run(dot))

[[22. 28.]
 [49. 64.]]


In [19]:
m1 = tf.constant([[1,2], [3,4]])
m2 = tf.constant([[5,6], [7,8]])

In [22]:
#e1 = tf.einsum('ij->ji', m1)
e2 = tf.einsum('ij,jk->ik', m1, m2)

In [23]:
with tf.Session() as sess:
    #print(sess.run(e1))
    print(sess.run(e2))

[[19 22]
 [43 50]]
