In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: user 16.9 ms, sys: 11.4 ms, total: 28.3 ms
Wall time: 34.7 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 1.75 s, sys: 312 ms, total: 2.06 s
Wall time: 2.64 s


In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[-0.41478199,  0.15197941, -0.52370887],
       [ 0.91864879,  0.90971506, -1.030536  ]])

In [8]:
data * 100

array([[ -41.47819851,   15.19794119,  -52.37088662],
       [  91.86487852,   90.97150617, -103.05359961]])

In [9]:
data + data

array([[-0.82956397,  0.30395882, -1.04741773],
       [ 1.83729757,  1.81943012, -2.06107199]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int64')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2,3,2))

array([[[4.66485933e-310, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr = np.empty((8, 4))

In [27]:
for i in range(8):
    arr[i] = i

In [28]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [29]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [30]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [31]:
arr = np.arange(32).reshape((8,4))

In [32]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [37]:
arr1 = arr[[1,5,7,2]]

In [38]:
arr1

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [39]:
arr1[[0,3,1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [40]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [42]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [43]:
arr = np.arange(15).reshape((3,5))

In [44]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [46]:
arr = np.arange(16).reshape((2,2,4))

In [47]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [48]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [55]:
x = np.arange(6).reshape(1,2,3)

In [56]:
x

array([[[0, 1, 2],
        [3, 4, 5]]])

In [57]:
np.transpose(x, (1,0,2))

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [58]:
np.transpose(x, (1,0,2)).shape

(2, 1, 3)

In [59]:
arr = np.arange(10)

In [60]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [62]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [63]:
x = np.random.randn(8)

In [64]:
y = np.random.randn(8)

In [65]:
x

array([ 1.30942082, -0.26437476,  0.92364427, -0.30635736, -0.10105691,
        0.29001666,  0.79919612,  0.05582268])

In [66]:
y

array([-0.73061611, -0.57366941, -0.11489927, -0.57876321, -1.03897678,
        1.23938044, -1.5003311 ,  0.67117956])

In [67]:
np.maximum(x,y)

array([ 1.30942082, -0.26437476,  0.92364427, -0.30635736, -0.10105691,
        1.23938044,  0.79919612,  0.67117956])

In [68]:
arr = np.random.randn(7)

In [69]:
arr

array([-0.18633707,  0.04302082,  0.14684871, -0.76385343, -0.26421574,
        0.71094501,  1.52542301])

In [70]:
arr = arr * 5

In [71]:
arr

array([-0.93168535,  0.21510411,  0.73424354, -3.81926716, -1.3210787 ,
        3.55472505,  7.62711505])

In [72]:
remainder, whole_part = np.modf(arr)

In [73]:
remainder

array([-0.93168535,  0.21510411,  0.73424354, -0.81926716, -0.3210787 ,
        0.55472505,  0.62711505])

In [74]:
whole_part

array([-0.,  0.,  0., -3., -1.,  3.,  7.])