In [1]:
import tensorflow as tf

In [2]:
sess = tf.Session()

In [3]:
import numpy as np

In [4]:
x_vals = np.array([1., 3., 5., 7., 9.])

In [8]:
x_data = tf.placeholder(tf.float32)

In [9]:
m_const = tf.constant(3.)

In [10]:
my_product = tf.multiply(x_data, m_const)

In [11]:
for x_val in x_vals:
    print(sess.run(my_product, feed_dict={x_data: x_val}))

3.0
9.0
15.0
21.0
27.0


In [12]:
my_array = np.array([[1., 3., 5., 7., 9.], [-2., 0., 2., 4., 6.], [-6., -3., 0., 3., 6.]])

In [13]:
my_array

array([[ 1.,  3.,  5.,  7.,  9.],
       [-2.,  0.,  2.,  4.,  6.],
       [-6., -3.,  0.,  3.,  6.]])

In [14]:
x_vals = np.array([my_array, my_array + 1])

In [15]:
x_vals

array([[[ 1.,  3.,  5.,  7.,  9.],
        [-2.,  0.,  2.,  4.,  6.],
        [-6., -3.,  0.,  3.,  6.]],

       [[ 2.,  4.,  6.,  8., 10.],
        [-1.,  1.,  3.,  5.,  7.],
        [-5., -2.,  1.,  4.,  7.]]])

In [16]:
x_vals.shape

(2, 3, 5)

In [18]:
x_data = tf.placeholder(tf.float32, shape=(3,5))

m1 = tf.constant([1.], [0.], [-1.], [2.], [4.]])

In [19]:
m1 = tf.constant([[1.], [0.], [-1.], [2.], [4.]])

In [20]:
m2 = tf.constant([[2.]])

In [21]:
m3 = tf.constant([[10.]])

In [22]:
prod1 = tf.matmul(x_data, m1)

In [23]:
prod2 = tf.matmul(prod1, m2)

In [24]:
add1 = tf.add(prod2, m3)

In [25]:
for x_val in x_vals:
    print(sess.run(add1, feed_dict={x_data: x_val}))

[[102.]
 [ 66.]
 [ 58.]]
[[114.]
 [ 78.]
 [ 70.]]


In [26]:
m1

<tf.Tensor 'Const_2:0' shape=(5, 1) dtype=float32>

In [27]:
x_shape = [1, 4, 4, 1]

In [28]:
x_val = np.random.uniform(size=x_shape)

In [29]:
x_data = tf.placeholder(tf.float32, shape=x_shape)

In [30]:
my_filter = tf.constant(0.25, shape=[2, 2, 1, 1])

In [31]:
my_strides = [1, 2, 2, 1]

In [32]:
mov_avg_layer = tf.nn.conv2d(x_data, my_filter, my_strides, padding='SAME', name='Moving_Avg_Window')