In [7]:
import tensorflow as tf
import numpy as np

In [8]:
identity_matrix = tf.diag([1.0, 1.0, 1.0])

In [9]:
A = tf.truncated_normal([2, 3])

In [10]:
B = tf.fill([2,3], 5.0)

In [11]:
C = tf.random_uniform([3,2])

In [12]:
D = tf.convert_to_tensor(np.array([[1., 2., 3.], [-3., -7., -1.], [0., 5., -2.]]))

In [13]:
sess = tf.Session()

In [14]:
print(sess.run(identity_matrix))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
print(sess.run(A))

[[-0.4400782  -1.0286944   0.4598479 ]
 [ 0.8664809  -0.11947782 -0.07496538]]


In [16]:
print(sess.run(B))

[[5. 5. 5.]
 [5. 5. 5.]]


In [17]:
print(sess.run(C))

[[0.15823591 0.67416275]
 [0.91631866 0.81547356]
 [0.5410199  0.15894818]]


In [18]:
print(sess.run(D))

[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


In [19]:
print(sess.run(A+B))

[[6.2863216 5.6850233 4.655763 ]
 [4.4813557 5.1870494 4.333559 ]]


In [20]:
print(sess.run(B-B))

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
print(sess.run(tf.matmul(B, identity_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


In [22]:
print(sess.run(tf.transpose(C)))

[[0.8225721  0.8124782  0.5415007 ]
 [0.23650515 0.762535   0.94065607]]


In [23]:
print(sess.run(tf.matrix_determinant(D)))

-37.99999999999999


In [24]:
print(sess.run(tf.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [25]:
print(sess.run(tf.self_adjoint_eig(D)))

(array([-10.65907521,  -0.22750691,   2.88658212]), array([[ 0.21749542,  0.63250104, -0.74339638],
       [ 0.84526515,  0.2587998 ,  0.46749277],
       [-0.4880805 ,  0.73004459,  0.47834331]]))


In [26]:
print(sess.run(tf.self_adjoint_eigvals(D)))

[-10.65907521  -0.22750691   2.88658212]


In [27]:
print(sess.run(tf.div(3, 4)))

0


In [29]:
print(sess.run(tf.truediv(3, 4)))

0.75


In [30]:
print(sess.run(tf.floordiv(3.0, 4.0)))

0.0


In [31]:
print(sess.run(tf.mod(22.0, 5.0)))

2.0


In [32]:
print(sess.run(tf.cross([1., 0., 0.], [0., 1., 0.])))

[0. 0. 1.]


In [33]:
print(sess.run(tf.exp(1.)))

2.7182817


In [35]:
print(sess.run(tf.pow(2., 3)))

8.0


In [36]:
print(sess.run(tf.rsqrt(4.)))

0.5


In [38]:
print(sess.run(tf.square(2)))

4


In [39]:
print(sess.run(tf.tan(3.1416/4.)))

1.0000036


In [42]:
def polynomial1(value):
    return (3*tf.square(value) - value) + 10

In [43]:
print(sess.run(polynomial1(11)))

362


In [44]:
print(sess.run(tf.nn.relu([-3., 3., 10.])))

[ 0.  3. 10.]


In [45]:
print(sess.run(tf.nn.relu6([-3., 3., 10.])))

[0. 3. 6.]


In [46]:
print(sess.run(tf.nn.sigmoid([-1., 0., 1.])))

[0.26894143 0.5        0.7310586 ]


In [47]:
print(sess.run(tf.nn.tanh([-1., 0., 1.])))

[-0.7615942  0.         0.7615942]


In [49]:
print(sess.run(tf.nn.softsign([-10., 0., 10.])))

[-0.90909094  0.          0.90909094]


In [50]:
print(sess.run(tf.nn.softplus([-1., 0., 1.])))

[0.31326166 0.6931472  1.3132616 ]


In [51]:
print(sess.run(tf.nn.elu([-1., 0., 1.])))

[-0.63212055  0.          1.        ]


In [52]:
from sklearn import datasets

In [53]:
iris = datasets.load_iris()

In [54]:
print(len(iris.data))

150


In [55]:
print(len(iris.target))

150


In [56]:
print(set(iris.target))

{0, 1, 2}


In [57]:
import requests

In [58]:
birthdata_url = 'https://raw.githubusercontent.com/nfmcclure/tensorflow_cookbook/master/01_Introduction/07_Working_with_Data_Sources/birthweight_data/birthweight.dat'

In [59]:
birth_file = requests.get(birthdata_url)

In [60]:
birth_data = birth_file.text.split('\r\n')

In [61]:
birth_header = birth_data[0].split('\t')

In [62]:
birth_data = [[float(x) for x in y.split('\t') if len(x) >= 1] for y in birth_data[1:] if len(y) >= 1]

In [63]:
print(len(birth_data))

189


In [64]:
print(len(birth_data[0]))

9


In [65]:
from keras.datasets import boston_housing

In [66]:
(x_train, y_tain), (x_test, y_test) = boston_housing.load_data()

57344/57026 [==============================] - 0s 5us/step


In [67]:
housing_header = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

In [68]:
print(x_train.shape[0])

404


In [69]:
print(x_train.shape[1])

13


In [70]:
from tensorflow.examples.tutorials.mnist import input_datata

In [72]:
mnist = tf.keras.datasets.mnist

In [75]:
(x_train, y_train), (x_test, y_test) = mnist.load_data(path='/home/sha/data/mnist.npz')

In [77]:
import io

In [78]:
from zipfile import ZipFile

In [79]:
zip_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00228/smsspamcollection.zip'

In [80]:
r = requests.get(zip_url)

In [81]:
z = ZipFile(io.BytesIO(r.content))

In [82]:
file = z.read('SMSSpamCollection')

In [83]:
text_data = file.decode()

In [84]:
text_data = text_data.encode('ascii', errors='ignore')

In [85]:
text_data = text_data.decode().split('\n')

In [86]:
text_data = [x.split('\t') for x in text_data if len(x) >= 1]

In [87]:
[text_data_target, text_data_train] = [list(x) for x in zip(*text_data)]

In [88]:
print(len(text_data_train))

5574


In [89]:
print(set(text_data_target))

{'spam', 'ham'}


In [90]:
print(text_data_train[1])

Ok lar... Joking wif u oni...


In [91]:
import tarfile

In [92]:
movie_data_url = 'http://www.cs.cornell.edu/people/pabo/movie-review-data/rt-polaritydata.tar.gz'

In [99]:
r = requests.get(movie_data_url)

In [102]:
stream_data = io.BytesIO(r.content)
tmp = io.BytesIO()

In [103]:
while True:
    s = stream_data.read(16384)
    if not s:
        break
    tmp.write(s)
stream_data.close()
tmp.seek(0)

0

In [104]:
tar_file = tarfile.open(fileobj=tmp, mode='r:gz')

In [105]:
pos = tar_file.extractfile('rt-polaritydata/rt-polarity.pos')

In [106]:
neg = tar_file.extractfile('rt-polaritydata/rt-polarity.neg')

In [107]:
pos_data = []

In [108]:
for line in pos:
    pos_data.append(line.decode('ISO-8859-1').encode('ascii', errors='ignore').decode())

In [109]:
neg_data = []
for line in neg:
    neg_data.append(line.decode('ISO-8859-1').encode('ascii', errors='ignore').decode())

In [110]:
tar_file.close()

In [111]:
print(len(pos_data))

5331


In [112]:
print(len(neg_data))

5331


In [113]:
print(neg_data[0])

simplistic , silly and tedious . 



In [114]:
import requests

In [117]:
shakespeare_url = 'http://www.gutenberg.org/cache/epub/100/pg100.txt'
shakespeare_url = '/home/sha/data/pg100.txt'

In [118]:
#r = requests.get(shakespeare_url)

In [129]:
with open(shakespeare_url, 'r', encoding='utf-8') as myfile:
    data=myfile.read()

In [130]:
print(len(data))

5465100


In [131]:
shakespeare_text = data[170:]

In [132]:
print(len(shakespeare_text))

5464930


In [133]:
import requests
import io

In [134]:
from zipfile import ZipFile

In [135]:
sentence_url = 'http://www.manythings.org/anki/cmn-eng.zip'

In [136]:
r = requests.get(sentence_url)

In [137]:
z = ZipFile(io.BytesIO(r.content))

In [138]:
file = z.read('cmn.txt')

In [139]:
eng_cmn_data = file.decode()

In [140]:
eng_cmn_data = eng_cmn_data.encode('utf-8')

In [141]:
eng_cmn_data = eng_cmn_data.decode().split('\n')

In [142]:
eng_cmn_data = [x.split('\t') for x in eng_cmn_data if len(x) >= 1]

In [143]:
[english_sentence, chinese_sentence] = [list(x) for x in zip(*eng_cmn_data)]

In [144]:
print(len(english_sentence))

20294


In [145]:
print(len(chinese_sentence))

20294


In [146]:
print(eng_cmn_data[10])

['Hop in.', '跳进来。']
